export const packages = [
  {
    tier: "Package 1",
    name: "Essential Storage",
    price: "£8,260",
    highlight: false,
    color: "green",
    panels: "8 Premium Solar Panels",
    system: "Approx. 3.64 kWp",
    battery: "Fox ESS EP6 · 5.76 kWh Li-ion (with heating function)",
    inverter: "Fox ESS H1-3.68 Single Phase Hybrid Inverter (3.60 kW)",
    blurb: "Ideal for smaller households looking to reduce electricity bills and store excess solar energy.",
  },
  {
    tier: "Package 2",
    name: "Most Popular",
    price: "£9,300",
    highlight: true,
    color: "navy",
    panels: "12 Premium Solar Panels",
    system: "Approx. 5.46 kWp",
    battery: "Fox ESS EP6 · 5.76 kWh Li-ion (with heating function)",
    inverter: "Fox ESS H1-3.7-E-G2 Single Phase Hybrid Inverter",
    blurb: "A balanced solution providing excellent daytime generation and battery storage for typical family homes.",
  },
  {
    tier: "Package 3",
    name: "Maximum Energy Independence",
    price: "£11,560",
    highlight: false,
    color: "orange",
    panels: "12–14 Premium Solar Panels",
    system: "5.46 – 6.37 kWp (depending on roof space)",
    battery: "Fox ESS EP12 · 11.52 kWh Li-ion (with heating function)",
    inverter: "Fox ESS H1-3.7-E-G2 Single Phase Hybrid Inverter",
    blurb: "Perfect for larger family homes, EV charging, heat pump users, and maximum independence.",
  },
  {
    tier: "Package 4",
    name: "Bespoke Survey & Design",
    price: "Custom",
    highlight: false,
    color: "red",
    panels: "Tailored to your property",
    system: "Homes · Shops · Farms · Commercial",
    battery: "Battery Storage Recommendations",
    inverter: "Systems up to 50 kW+ and beyond",
    blurb: "Our surveyor assesses your property and provides a tailored Solar PV & Battery Storage proposal.",
  },
] as const;

export const included = [
  "Scaffolding",
  "Roof mounting system, rails & fixings",
  "Bird protection mesh",
  "Electrical installation",
  "System commissioning",
  "DNO application / notification",
  "MCS certification",
  "Monitoring setup",
  "Manufacturer warranties",
  "Workmanship warranty",
  "Customer handover pack",
];

export const finance = [
  { name: "0% APR Finance", years: "1–3 Years", features: ["No interest charged", "£500 administration fee", "Simple & affordable payments", "Subject to approval"] },
  { name: "5 Year Finance", years: "5 Years", features: ["Subject to credit approval", "Representative APR up to 11.9%", "Spread the cost with manageable payments"] },
  { name: "10 Year Finance", years: "10 Years", features: ["Subject to credit approval", "Representative APR up to 11.9%", "Lowest monthly payments"] },
];

export const faqs = [
  { q: "How much can I save with solar panels?", a: "Savings depend on your roof size, energy usage and tariff. A typical UK home saves £700–£1,400 per year. Our free survey provides a personalised estimate." },
  { q: "Do solar panels work in winter or cloudy weather?", a: "Yes. Panels generate electricity from daylight, not heat, so they still produce power on overcast days — just at reduced output." },
  { q: "How long does installation take?", a: "Most domestic installations take 1–2 days. Larger commercial jobs may take longer depending on scale." },
  { q: "Do I need planning permission?", a: "For most homes, no. Solar PV is usually permitted development. We advise on your specific case during the free survey." },
  { q: "Do you offer finance?", a: "Yes. We offer 0% APR (1–3 years), 5-year, and 10-year finance options, subject to credit approval." },
  { q: "What warranties are included?", a: "You get manufacturer warranties on panels (up to 25 years performance), a 10-year battery warranty, plus our workmanship guarantee." },
  { q: "Are you MCS certified?", a: "Yes. Apex Aims Grants Ltd is a fully MCS-certified installer — required for SEG (Smart Export Guarantee) payments and quality assurance." },
  { q: "Can I sell electricity back to the grid?", a: "Yes, through the Smart Export Guarantee (SEG). We register your system so you get paid for the surplus you export." },
  { q: "How long do solar panels last?", a: "Quality panels have a 25–30 year lifespan, typically producing 80%+ of their rated output at year 25." },
  { q: "Do panels damage the roof?", a: "No. Installed correctly with the proper mounting kit and flashings, panels actually protect the roof beneath them." },
  { q: "What roof types can you install on?", a: "Slate, tile, metal, flat felt or membrane. We survey the roof condition and recommend the best mounting solution." },
  { q: "Do I need a south-facing roof?", a: "South is optimal, but east/west orientations still generate 80–85%. We model your specific roof during the design phase." },
  { q: "What is a hybrid inverter?", a: "A hybrid inverter manages solar generation, battery storage and grid supply in one unit — the standard for modern solar + battery systems." },
  { q: "How big a battery do I need?", a: "Typical homes benefit from 5–12 kWh. Larger households, EV owners or heat pump users may want more. Our design considers usage patterns and tariffs." },
  { q: "Can I charge my EV with solar?", a: "Yes. We integrate solar and EV charging so your car can be topped up on free sunshine when possible." },
  { q: "Do you install for landlords?", a: "Yes. Solar improves EPC ratings, reduces tenant bills and can protect against future MEES regulation changes." },
  { q: "Is there a payback period?", a: "Typical payback in the UK is 6–10 years, then decades of near-free electricity. Battery-only paybacks depend on tariff arbitrage." },
  { q: "What maintenance is needed?", a: "Very little. An annual visual check, occasional cleaning, and remote monitoring keep the system healthy." },
  { q: "What happens in a power cut?", a: "Standard grid-tied inverters shut off for safety. With a suitable battery + EPS/backup circuit, essential loads can keep running." },
  { q: "Can I monitor the system?", a: "Yes. Fox ESS apps show live generation, consumption and battery state on your phone." },
  { q: "Do I need to tell my energy supplier?", a: "We handle the DNO notification and provide documentation you can share with your supplier for SEG registration." },
  { q: "Are there any grants available?", a: "Grants change frequently. We advise on ECO4, Great British Insulation Scheme and Home Upgrade Grant eligibility during your survey." },
  { q: "How noisy are batteries and inverters?", a: "Very quiet — typically a soft fan hum under load. We site them thoughtfully to keep living areas peaceful." },
  { q: "Can I add more panels later?", a: "Often yes, if the inverter has spare capacity or a second string. We design with future expansion in mind where possible." },
  { q: "Does bird protection come as standard?", a: "Yes. All our installs include bird protection mesh to prevent pigeons nesting under the panels." },
  { q: "How is the system installed safely?", a: "Full scaffolding, harnesses, and site risk assessments. All electrical work is certified and NICEIC standard." },
  { q: "Do you offer commercial solar?", a: "Yes — offices, warehouses, farms, retail and industrial. Systems up to 50 kW+ with tailored ROI analysis." },
  { q: "What is the SEG and how much does it pay?", a: "Smart Export Guarantee pays for electricity exported to the grid. Rates vary by supplier — typically 5p–15p per kWh in 2025." },
  { q: "Do panels increase my house value?", a: "Studies suggest solar can add 1–4% to property value and make homes more sellable." },
  { q: "Can I combine solar with a heat pump?", a: "Absolutely. Solar + heat pump is one of the most effective long-term energy strategies for UK homes." },
  { q: "Will hail or snow damage the panels?", a: "Panels are tested to withstand hail and heavy snow loads. Snow generally slides off due to the tilt angle." },
  { q: "Do you install in listed buildings or conservation areas?", a: "It depends. Planning consent is usually required — we help navigate the process." },
  { q: "How quickly can you install?", a: "Typically 4–8 weeks from survey to install, subject to scaffolding, DNO and material lead times." },
  { q: "What areas do you cover?", a: "We install across the UK, with core coverage of London, the South East and East of England from our Ilford base." },
  { q: "Do you use quality components?", a: "Yes. Tier-1 panels, Fox ESS inverters and batteries, and MCS-approved mounting systems." },
  { q: "Is the deposit refundable?", a: "Deposits are held under our terms. Cooling-off periods apply per Consumer Contracts Regulations." },
  { q: "What if my roof needs repair first?", a: "We flag any concerns at survey and can recommend trusted trades. Panels should always be installed on a sound roof." },
  { q: "Do I need permission from my mortgage lender?", a: "Some lenders ask to be informed. We can provide the paperwork; most consent without issue." },
  { q: "Can flats or shared roofs have solar?", a: "It's possible with freeholder consent and shared metering agreements — get in touch to explore options." },
  { q: "Do you handle scaffolding?", a: "Yes. Scaffolding is included in every installation package we quote." },
  { q: "What certifications do your installers hold?", a: "MCS, NICEIC, RECC, plus manufacturer training on Fox ESS and other approved products." },
  { q: "How do I pay?", a: "Bank transfer, card, or via one of our finance partners. A schedule is set out in your contract." },
  { q: "Can you remove panels for a re-roof?", a: "Yes. We can uninstall and refit panels around roofing works — get a tailored quote." },
  { q: "Is my data safe when I enquire?", a: "Yes. See our Privacy Policy — we only use your data to respond to your enquiry and never sell it." },
  { q: "What's next after I book a survey?", a: "We confirm a time, visit or remote-survey your property, then send a written proposal within a few working days." },
];
